services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}

volumes:
  pgdata: {}