services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}