CREATE TABLE IF NOT EXISTS sales (
    DATA_VENDA DATE NOT NULL,
    ID_FILIAL INT NOT NULL,
    PRODUTO VARCHAR(50) NOT NULL,
    COR_PRODUTO VARCHAR(50),
    TAMANHO VARCHAR(10),
    VENDA_PECAS INT,
    VENDA_LIQUIDA DECIMAL(10, 2),
    VENDA_BRUTA DECIMAL(10, 2)
);