CREATE TABLE IF NOT EXISTS sales_velocity (
    DATA_VENDA DATE,
    ID_FILIAL INT,
    PRODUTO VARCHAR(255),
    COR_PRODUTO VARCHAR(255),
    TAMANHO VARCHAR(255),
    VENDA_PECAS INT,
    VENDA_LIQUIDA NUMERIC,
    VENDA_BRUTA NUMERIC,
    ESTOQUE_DISPONIVEL INT,
    VELOCIDADE_VENDA DECIMAL
);