CREATE TABLE IF NOT EXISTS stock (
    DATA_FOTO DATE NOT NULL,
    ID_FILIAL INT NOT NULL,
    PRODUTO VARCHAR(50) NOT NULL,
    COR_PRODUTO VARCHAR(50) NOT NULL,
    TAMANHO CHAR(50) NOT NULL,
    TOTAL INT NOT NULL,
    TRANSITO INT NOT NULL
);
