CREATE TABLE IF NOT EXISTS products (
    ARTIGO_COR VARCHAR(50) NOT NULL,
    ARTIGO VARCHAR(50) NOT NULL,
    DESC_PRODUTO VARCHAR(200) NOT NULL,
    COR VARCHAR(50),
    COR_DESCRICAO VARCHAR(200),
    NEGOCIO VARCHAR(100),
    PARTE VARCHAR(100),
    GRUPO VARCHAR(100),
    GENERO VARCHAR(50),
    COD_COTA INT,
    COLECAO VARCHAR(50),
    PIRAMIDE VARCHAR(50)
);
